// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { ListJointsJointsIndexGetData, ListJointsJointsIndexGetResponses, MoveJointJointsJointNameMovePostData, MoveJointJointsJointNameMovePostResponses, MoveJointJointsJointNameMovePostErrors, StopJointJointsJointNameStopPostData, StopJointJointsJointNameStopPostResponses, StopJointJointsJointNameStopPostErrors, StatusJointJointsJointNameStatusGetData, StatusJointJointsJointNameStatusGetResponses, StatusJointJointsJointNameStatusGetErrors, ArmAllJointsArmAllPostData, ArmAllJointsArmAllPostResponses, DisarmAllJointsDisarmAllPostData, DisarmAllJointsDisarmAllPostResponses, CalibrateJointJointsJointNameCalibratePostData, CalibrateJointJointsJointNameCalibratePostResponses, CalibrateJointJointsJointNameCalibratePostErrors, ConfigureJointJointsJointNameConfigurePostData, ConfigureJointJointsJointNameConfigurePostResponses, ConfigureJointJointsJointNameConfigurePostErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all configured joints
 * Return a list of all registered joints and their metadata.
 */
export const listJointsJointsIndexGet = <ThrowOnError extends boolean = false>(options?: Options<ListJointsJointsIndexGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListJointsJointsIndexGetResponses, unknown, ThrowOnError>({
        url: '/joints/index',
        ...options
    });
};

/**
 * Move Joint
 */
export const moveJointJointsJointNameMovePost = <ThrowOnError extends boolean = false>(options: Options<MoveJointJointsJointNameMovePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MoveJointJointsJointNameMovePostResponses, MoveJointJointsJointNameMovePostErrors, ThrowOnError>({
        url: '/joints/{joint_name}/move',
        ...options
    });
};

/**
 * Stop Joint
 */
export const stopJointJointsJointNameStopPost = <ThrowOnError extends boolean = false>(options: Options<StopJointJointsJointNameStopPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<StopJointJointsJointNameStopPostResponses, StopJointJointsJointNameStopPostErrors, ThrowOnError>({
        url: '/joints/{joint_name}/stop',
        ...options
    });
};

/**
 * Status Joint
 */
export const statusJointJointsJointNameStatusGet = <ThrowOnError extends boolean = false>(options: Options<StatusJointJointsJointNameStatusGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<StatusJointJointsJointNameStatusGetResponses, StatusJointJointsJointNameStatusGetErrors, ThrowOnError>({
        url: '/joints/{joint_name}/status',
        ...options
    });
};

/**
 * Arm All
 */
export const armAllJointsArmAllPost = <ThrowOnError extends boolean = false>(options?: Options<ArmAllJointsArmAllPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<ArmAllJointsArmAllPostResponses, unknown, ThrowOnError>({
        url: '/joints/arm-all',
        ...options
    });
};

/**
 * Disarm All
 */
export const disarmAllJointsDisarmAllPost = <ThrowOnError extends boolean = false>(options?: Options<DisarmAllJointsDisarmAllPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DisarmAllJointsDisarmAllPostResponses, unknown, ThrowOnError>({
        url: '/joints/disarm-all',
        ...options
    });
};

/**
 * Calibrate Joint
 */
export const calibrateJointJointsJointNameCalibratePost = <ThrowOnError extends boolean = false>(options: Options<CalibrateJointJointsJointNameCalibratePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CalibrateJointJointsJointNameCalibratePostResponses, CalibrateJointJointsJointNameCalibratePostErrors, ThrowOnError>({
        url: '/joints/{joint_name}/calibrate',
        ...options
    });
};

/**
 * Configure Joint
 */
export const configureJointJointsJointNameConfigurePost = <ThrowOnError extends boolean = false>(options: Options<ConfigureJointJointsJointNameConfigurePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ConfigureJointJointsJointNameConfigurePostResponses, ConfigureJointJointsJointNameConfigurePostErrors, ThrowOnError>({
        url: '/joints/{joint_name}/configure',
        ...options
    });
};