// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ListJointsJointsIndexGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/joints/index';
};

export type ListJointsJointsIndexGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MoveJointJointsJointNameMovePostData = {
    body?: never;
    path: {
        /**
         * Joint Name
         */
        joint_name: string;
    };
    query: {
        /**
         * Position
         */
        position: number;
        /**
         * Velocity
         */
        velocity?: number;
        /**
         * Accel
         */
        accel?: number;
        /**
         * Hold
         */
        hold?: boolean;
    };
    url: '/joints/{joint_name}/move';
};

export type MoveJointJointsJointNameMovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MoveJointJointsJointNameMovePostError = MoveJointJointsJointNameMovePostErrors[keyof MoveJointJointsJointNameMovePostErrors];

export type MoveJointJointsJointNameMovePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StopJointJointsJointNameStopPostData = {
    body?: never;
    path: {
        /**
         * Joint Name
         */
        joint_name: string;
    };
    query?: never;
    url: '/joints/{joint_name}/stop';
};

export type StopJointJointsJointNameStopPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopJointJointsJointNameStopPostError = StopJointJointsJointNameStopPostErrors[keyof StopJointJointsJointNameStopPostErrors];

export type StopJointJointsJointNameStopPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StatusJointJointsJointNameStatusGetData = {
    body?: never;
    path: {
        /**
         * Joint Name
         */
        joint_name: string;
    };
    query?: never;
    url: '/joints/{joint_name}/status';
};

export type StatusJointJointsJointNameStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StatusJointJointsJointNameStatusGetError = StatusJointJointsJointNameStatusGetErrors[keyof StatusJointJointsJointNameStatusGetErrors];

export type StatusJointJointsJointNameStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ArmAllJointsArmAllPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/joints/arm-all';
};

export type ArmAllJointsArmAllPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DisarmAllJointsDisarmAllPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/joints/disarm-all';
};

export type DisarmAllJointsDisarmAllPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CalibrateJointJointsJointNameCalibratePostData = {
    body?: never;
    path: {
        /**
         * Joint Name
         */
        joint_name: string;
    };
    query?: {
        /**
         * State
         */
        state?: number;
        /**
         * Save Config
         */
        save_config?: boolean;
    };
    url: '/joints/{joint_name}/calibrate';
};

export type CalibrateJointJointsJointNameCalibratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CalibrateJointJointsJointNameCalibratePostError = CalibrateJointJointsJointNameCalibratePostErrors[keyof CalibrateJointJointsJointNameCalibratePostErrors];

export type CalibrateJointJointsJointNameCalibratePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ConfigureJointJointsJointNameConfigurePostData = {
    body?: never;
    path: {
        /**
         * Joint Name
         */
        joint_name: string;
    };
    query?: {
        /**
         * Save Config
         * If true, save to NVM & reboot
         */
        save_config?: boolean;
    };
    url: '/joints/{joint_name}/configure';
};

export type ConfigureJointJointsJointNameConfigurePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfigureJointJointsJointNameConfigurePostError = ConfigureJointJointsJointNameConfigurePostErrors[keyof ConfigureJointJointsJointNameConfigurePostErrors];

export type ConfigureJointJointsJointNameConfigurePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};